In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = sns.load_dataset('titanic')

In [4]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [5]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [6]:
df.drop(['deck','embark_town',
         'alive','alone','class','who'],axis=1,inplace=True)

In [7]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male
0,0,3,male,22.0,1,0,7.2500,S,True
1,1,1,female,38.0,1,0,71.2833,C,False
2,1,3,female,26.0,0,0,7.9250,S,False
3,1,1,female,35.0,1,0,53.1000,S,False
4,0,3,male,35.0,0,0,8.0500,S,True
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,True
887,1,1,female,19.0,0,0,30.0000,S,False
888,0,3,female,NaN,1,2,23.4500,S,False
889,1,1,male,26.0,0,0,30.0000,C,True
890,0,3,male,32.0,0,0,7.7500,Q,True

In [8]:
df['age'] = df['age'].fillna(df['age'].mean())

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   survived    891 non-null    int64
 1   pclass      891 non-null    int64
 2   sex         891 non-null    object
 3   age         891 non-null    float64
 4   sibsp       891 non-null    int64
 5   parch       891 non-null    int64
 6   fare        891 non-null    float64
 7   embarked    889 non-null    object
 8   adult_male  891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [10]:
df.dropna(subset=["embarked"],inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   survived    889 non-null    int64
 1   pclass      889 non-null    int64
 2   sex         889 non-null    object
 3   age         889 non-null    float64
 4   sibsp       889 non-null    int64
 5   parch       889 non-null    int64
 6   fare        889 non-null    float64
 7   embarked    889 non-null    object
 8   adult_male  889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [12]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()

In [13]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  adult_male
0         0       3    male  22.0      1      0   7.2500        S        True
1         1       1  female  38.0      1      0  71.2833        C       False
2         1       3  female  26.0      0      0   7.9250        S       False
3         1       1  female  35.0      1      0  53.1000        S       False
4         0       3    male  35.0      0      0   8.0500        S        True

In [14]:
df['sex'] = le.fit_transform(df["sex"])

In [15]:
df = pd.get_dummies(df, columns=['embarked'],drop_first=True, prefix='embarked', dtype=int)

In [16]:
df.astype(int)

,survived,pclass,sex,age,sibsp,parch,fare,adult_male,embarked_Q,embarked_S
0,0,3,1,22,1,0,7,1,0,1
1,1,1,0,38,1,0,71,0,0,0
2,1,3,0,26,0,0,7,0,0,1
3,1,1,0,35,1,0,53,0,0,1
4,0,3,1,35,0,0,8,1,0,1
...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27,0,0,13,1,0,1
887,1,1,0,19,0,0,30,0,0,1
888,0,3,0,29,1,2,23,0,0,1
889,1,1,1,26,0,0,30,1,0,0
890,0,3,1,32,0,0,7,1,1,0

In [17]:
X = df.drop(columns=["survived"])
y = df["survived"]

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42)

In [19]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train,y_train)

LogisticRegression()

In [20]:
y_pred = model.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score, classification_report , confusion_matrix

In [22]:
accuracy_score(y_test,y_pred)

0.8202247191011236

In [23]:
confusion_matrix(y_test, y_pred)

array([[91, 18],
       [14, 55]])

In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.83      0.85       109
           1       0.75      0.80      0.77        69

    accuracy                           0.82       178
   macro avg       0.81      0.82      0.81       178
weighted avg       0.82      0.82      0.82       178

In [25]:
from sklearn. preprocessing import StandardScaler
scaler = StandardScaler()

In [26]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [28]:
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [29]:
y_pred_knn = knn_model.predict(X_test)

In [30]:
y_pred_knn

array([0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1])

In [31]:
accuracy_score(y_test,y_pred_knn)

0.6404494382022472

In [32]:
from sklearn.naive_bayes import GaussianNB

model_NB = GaussianNB()

model_NB.fit(X_train, y_train)

GaussianNB()

In [33]:
y_pred_nb = model_NB.predict(X_test)

In [34]:
accuracy_score(y_test,y_pred_nb)

0.797752808988764

In [35]:
from sklearn.tree import DecisionTreeClassifier

In [36]:
model_DT = DecisionTreeClassifier(random_state=42)

In [37]:
model_DT.fit(X_train_scaled, y_train)

DecisionTreeClassifier(random_state=42)

In [38]:
y_pred_dtc = model_DT.predict(X_test_scaled)

In [39]:
accuracy_score(y_test, y_pred_dtc)

0.7640449438202247

In [40]:
from sklearn.svm import SVC
model_svc = SVC(kernel = 'rbf')
model_svc.fit(X_train_scaled, y_train)

SVC()

In [41]:
y_pred_svc = model_svc.predict(X_test_scaled)
accuracy_score(y_test, y_pred_svc)

0.8146067415730337

In [42]:
import joblib
joblib.dump(model_svc, 'SVC_titanic.pkl')
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(X.columns.to_list(), 'columns.pkl')

['columns.pkl']

In [43]:
df

,survived,pclass,sex,age,sibsp,parch,fare,adult_male,embarked_Q,embarked_S
0,0,3,1,22.000000,1,0,7.2500,True,0,1
1,1,1,0,38.000000,1,0,71.2833,False,0,0
2,1,3,0,26.000000,0,0,7.9250,False,0,1
3,1,1,0,35.000000,1,0,53.1000,False,0,1
4,0,3,1,35.000000,0,0,8.0500,True,0,1
...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,13.0000,True,0,1
887,1,1,0,19.000000,0,0,30.0000,False,0,1
888,0,3,0,29.699118,1,2,23.4500,False,0,1
889,1,1,1,26.000000,0,0,30.0000,True,0,0
890,0,3,1,32.000000,0,0,7.7500,True,1,0

In [44]:
X = df.drop('survived', axis = 1)
y = df['survived']

In [45]:
from sklearn.model_selection import cross_val_score

In [46]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [47]:
scores = cross_val_score(knn_model, X_scaled, y, cv = 5, scoring='accuracy')

In [48]:
scores

array([0.79213483, 0.78089888, 0.83146067, 0.80898876, 0.83050847])

In [49]:
avg = scores.mean()
avg

np.float64(0.8087983241287375)

In [50]:
df

,survived,pclass,sex,age,sibsp,parch,fare,adult_male,embarked_Q,embarked_S
0,0,3,1,22.000000,1,0,7.2500,True,0,1
1,1,1,0,38.000000,1,0,71.2833,False,0,0
2,1,3,0,26.000000,0,0,7.9250,False,0,1
3,1,1,0,35.000000,1,0,53.1000,False,0,1
4,0,3,1,35.000000,0,0,8.0500,True,0,1
...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,13.0000,True,0,1
887,1,1,0,19.000000,0,0,30.0000,False,0,1
888,0,3,0,29.699118,1,2,23.4500,False,0,1
889,1,1,1,26.000000,0,0,30.0000,True,0,0
890,0,3,1,32.000000,0,0,7.7500,True,1,0